### ISSUE TITLE
"start payout" button does not generate a transaction

### ISSUE THREAD

**Issue by auryn-macmillan** [TomAFrench/colony-safe-app#18]

**Comment by TomAFrench** [comment]
Are you sure? I'm getting a transaction popup whenever I try to start a payout.

**Comment by auryn-macmillan** [comment]
Ah, you're right. It just took a few seconds to pop up. I think I was a little impatient last time.

I just tried triggering a payout and the transaction reverted.
https://etherscan.io/tx/0x19b5cf0373b2c7fb4a8929f2df06b45a44760fe46c3ca6f6f18506affccbfdb3

**Comment by TomAFrench** [comment]
Yeah, there's a fair amount of requests shooting off in the background to build the proofs.

>I just tried triggering a payout and the transaction reverted.
https://etherscan.io/tx/0x19b5cf0373b2c7fb4a8929f2df06b45a44760fe46c3ca6f6f18506affccbfdb3

Hmm, I'm really not sure what could be going on in this case then. I've basically copied the rewards app code for starting a payout and everything looks correct.

**Comment by auryn-macmillan** [comment]
This appears to be working as expected. The issue was that there was a zero balance in rewards pot, as it had all been allocated to other payouts. We should make a separate issue for this.
