### ISSUE TITLE
Cannot mint tokens

### ISSUE THREAD

**Issue by auryn-macmillan** [TomAFrench/colony-safe-app#8]
Cannot mint tokens from a safe that has the root permission.

![Screen record from 2020-07-17 16 55 13](https://user-images.githubusercontent.com/8453294/87830130-6e320e80-c84e-11ea-9569-973125dec937.gif)

**Comment by TomAFrench** [comment]
Hmm ok. I've noticed a similar issue with setting permissions recently so will be looking into this tomorrow.
